info:
  app:
    name: test-client

server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  jackson:
    time-zone: GMT+8
    serialization:
      indent_output: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    initial-size: 10
    min-idle: 10
    max-active: 100
    maxWait: 60000
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    validation-query: SELECT 1 FROM DUAL
    validation-query-timeout: 20000

    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    max-evictable-idle-time-millis: 600000

    test-on-borrow: false
    test-on-return: false
    test-while-idle: true

#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:/ehcache.xml

  redis:
    database: 0                      # Redis数据库索引（默认为0）
    host: 127.0.0.1                 # Redis服务器地址
    port: 6379                        # Redis服务器端口
    password:                       # Redis服务器连接密码（默认为空）
    pool:
      max-active: 1000     # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1            # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10            # 连接池中的最大空闲连接
      min-idle: 2              # 连接池中的最小空闲连接
    timeout: 3000                      # 连接超时时间（毫秒）

  boot:
    admin:
      client:
        url: 'http://localhost:9000'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
