server:
  port: 8088
spring:
  datasource:
    default:
      driver-class-name: org.h2.Driver
      password: ''
      url: 'jdbc:h2:mem:'
      username: sa
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

auth:
  guest_password: guest
  guest_username: guest
  root_password: root
  root_username: root